INSTRUCTION_INPUT(ADD, "add", "Adds two values")
INSTRUCTION_INPUT(SUB, "sub", "Subtracts second value from the first")
INSTRUCTION_INPUT(MUL, "mul", "Multiplies two values")
INSTRUCTION_INPUT(DIV, "div", "Divides first value by the second")
INSTRUCTION_INPUT(MOV, "mov", "Moves data from one place to another")
INSTRUCTION_INPUT(LOAD, "load", "Loads data from memory")
INSTRUCTION_INPUT(STORE, "store", "Stores data into memory")
INSTRUCTION_INPUT(AND, "and", "Logical AND operation")
INSTRUCTION_INPUT(OR, "or", "Logical OR operation")
INSTRUCTION_INPUT(XOR, "xor", "Logical XOR operation")
INSTRUCTION_INPUT(SHL, "shift_left", "Shifts bits to the left")
INSTRUCTION_INPUT(SHR, "shift_right", "Shifts bits to the right")
INSTRUCTION_INPUT(JMP, "jump", "Jumps to a new instruction address")
INSTRUCTION_INPUT(CMP, "compare", "Compares two values")
INSTRUCTION_INPUT(CALL, "call", "Calls a function or subroutine")
INSTRUCTION_INPUT(RET, "return", "Returns from a function or subroutine")
INSTRUCTION_INPUT(PUSH, "push", "Pushes a value onto the stack")
INSTRUCTION_INPUT(POP, "pop", "Pops a value from the stack")
